spring:
  datasource:
    url: jdbc:mysql://localhost:3306/save_lifes  # Database URL
    username: root                      # Database username
    password: password                      # Database password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver class name
  jpa:
    hibernate:
      ddl-auto: update                           # Hibernate DDL mode
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Hibernate dialect for MySQL

